---
  info: 
    title: "Geeny HelloWorld Application Example"
    version: "1.0.0"
    description: "Geeny HelloWorld Application Example is a sample application which allows\nGeeny Developers to explore Geeny API and start developing geeny\napplications in the local environment. The main goal is to demonstrate the\nworkflow for consuming data from Geeny API. The data consists of message\nstreams, which are distributed in shards. To consume the messages, a per\nshard long polling is used."
  host: "localhost:8080"
  basePath: "/api"
  produces: 
    - "application/json"
  consumes: 
    - "application/json"
  schemes: 
    - "http"
  swagger: "2.0"
  paths: 
    /{message_type}/{shard_id}/messages: 
      x-swagger-router-controller: "messages"
      get: 
        security: 
          - 
            JWT: []
        tags: 
          - "messages"
        summary: "Retrieves the messages of a shard."
        operationId: "getMessages"
        parameters: 
          - 
            name: "message_type"
            in: "path"
            type: "string"
            format: "opaque"
            required: true
          - 
            name: "shard_id"
            in: "path"
            type: "string"
            format: "opaque"
            required: true
          - 
            name: "amount"
            in: "query"
            type: "integer"
            default: 20
        responses: 
          200: 
            description: "The Messages."
            schema: 
              $ref: "#/definitions/Messages"
          500: 
            description: "Internal server error."
            schema: 
              $ref: "#/definitions/Error"
    /{message_type}/shards: 
      x-swagger-router-controller: "shards"
      get: 
        security: 
          - 
            JWT: []
        tags: 
          - "shards"
        summary: "A list of message type shards."
        description: "Developers are able to fetch the list of shards for a message type. Shards are used to retrieve messages.\n"
        operationId: "getShards"
        parameters: 
          - 
            name: "message_type"
            in: "path"
            type: "string"
            format: "opaque"
            required: true
        responses: 
          200: 
            description: "Shard list."
            schema: 
              $ref: "#/definitions/ShardList"
          500: 
            description: "Internal server error."
            schema: 
              $ref: "#/definitions/Error"
    /swagger: 
      x-swagger-pipe: "swagger_raw"
  definitions: 
    Messages: 
      type: "object"
      properties: 
        messages: 
          type: "array"
          items: 
            $ref: "#/definitions/Message"
    Message: 
      type: "object"
      properties: 
        sequenceNumber: 
          type: "string"
          format: "opaque"
        thingId: 
          type: "string"
          format: "opaque"
        messageId: 
          type: "string"
          format: "opaque"
        userId: 
          type: "string"
          format: "opaque"
        payload: 
          type: "string"
          format: "binary"
    Shard: 
      type: "object"
      properties: 
        shardId: 
          type: "string"
          format: "opaque"
          description: "Unique ID of the shard."
    ShardList: 
      type: "object"
      properties: 
        shards: 
          type: "array"
          items: 
            $ref: "#/definitions/Shard"
    Error: 
      type: "object"
      properties: 
        code: 
          type: "integer"
          format: "int32"
          description: "Error code"
        message: 
          type: "string"
          format: "opaque"
          description: "Error message"
  responses: {}
  parameters: {}
  securityDefinitions: 
    JWT: 
      type: "apiKey"
      name: "Authorization"
      in: "header"
  tags: []
